### PR TITLE
Update driver to v4.3.9.3

### PR DESCRIPTION
**Pull request by bmx666**
I merge with the lastest driver from Realtek.

*Check and fix compilation* on **Desktop Ubuntu 14.04.03 LTS x64** with [Ubuntu kernels](http://kernel.ubuntu.com/~kernel-ppa/mainline/):
* 3.12.49
* 3.13.11
* 3.14.54
* 3.15.10
* 3.16.7
* 3.17.8
* 3.18.22
* 3.19.0
* 3.19.8
* 4.0.9
* 4.1.10
* 4.2.3

*Check and fix compilation* on **Boundary Devices Android 4.4.3 and 5.0.0** with [Boundary kernels](https://github.com/boundarydevices/linux-imx6):
* [boundary-imx-kk4.4.3_2.0.0-ga](http://github.com/boundarydevices/linux-imx6/tree/boundary-imx-kk4.4.3_2.0.0-ga)
* [boundary-imx-l5.0.0_1.0.0-ga](http://github.com/boundarydevices/linux-imx6/tree/boundary-imx-l5.0.0_1.0.0-ga)

*Tested* on **Desktop Ubuntu 14.04.03 LTS x64 (kernel 4.2.3)** and **Boundary Devices Android 4.4.3**

*Issue:* SoftAP not working with encryption WEP and WPA-PSK.

### CODE REVIEW

**Comment by lwfinger** [comment]
I will not merge fixes for Ubuntu kernels into my repo. The reason is that Ubuntu backports the API from new kernels into the older versions. Once you "fix" the source to build on Ubuntu, it breaks for the users of most other distros, including mine. If you want it to build on Ubuntu, either you track down the special Ubuntu symbol needed to allow building on all distros, or you are on your own.

Sorry to be so harsh, but I have wasted many hours with this incorrect practice by Ubuntu, and I have no interest in repeating that ever again!!

**Comment by bmx666** [comment]
> I will not merge fixes for Ubuntu kernels into my repo
Sorry for misunderstanding word *fix*. I just check compilation under different kernel versions and I don't add some special fixes for Ubuntu, I fix most of warnings calling incompotable pointer of functions ioctl80211 according kernel headers from [Linux Cross Reference Free Electrons](http://lxr.free-electrons.com/)

I can check compilation under other distros with different kernels and report.

**Comment by bmx666** [comment]
Verify compilation without flag *-DRTW_USE_CFG80211_STA_EVENT* [vanilla kernels](https://github.com/torvalds/linux):
* 2.6.37
* 2.6.38
* 2.6.39
* 3.0
* 3.1

Verify compilation [vanilla kernels](https://github.com/torvalds/linux):
* 3.2
* 3.3
* 3.4
* 3.5
* 3.6
* 3.7
* 3.8
* 3.9
* 3.10
* 3.11
* 3.12
* 3.13
* 3.14
* 3.15
* 3.16
* 3.17
* 3.18
* 3.19
* 4.0
* 4.1
* 4.2

**Comment by bmx666** [comment]
*Tested* on **OpenSUSE 13.2 x64 (kernel 4.1.0)** and **Gentoo x64 (kernel 4.0.5)**

*Issue:* SoftAP not working with encryption WEP and WPA-PSK.

**Pull request closed without merging**
